<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>rococoa-core</artifactId>

  <parent>
    <groupId>org.rococoa</groupId>
    <artifactId>rococoa-parent</artifactId>
    <version>0.8.7</version>
  </parent>

  <name>Rococoa Core</name>
  <packaging>jar</packaging>
  <url>https://github.com/umjammer/rococoa</url>

  <profiles>
    <profile>
      <id>test-standalone</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>3.1.0</version>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <java classname="Test1" fork="true">
                  <classpath>
                    <path location="${project.build.directory}/${project.artifactId}-${project.version}.jar"/>
                    <path location="${project.build.directory}/${project.artifactId}-${project.version}-tests.jar"/>
                    <path location="${net.java.dev.jna:jna:jar}"/>
                    <path location="${net.bytebuddy:byte-buddy:jar}"/>
                  </classpath>
                  <arg value="${value}" />
                </java>
              </target>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>env.JITPACK</name>
          <value>!true</value>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-clean-plugin</artifactId>
            <version>3.3.1</version>
            <configuration>
              <filesets>
                <fileset>
                  <directory>${basedir}</directory>
                  <includes>
                    <include>src/main/resources/librococoa.dylib</include>
                  </includes>
                </fileset>
              </filesets>
            </configuration>
          </plugin>

          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>1.0-alpha-11</version>
            <extensions>true</extensions>
            <configuration>
              <compilerProvider>generic-classic</compilerProvider>
              <compilerStartOptions>
                <compilerStartOption>-g -Wall -O2 -fomit-frame-pointer -fPIC</compilerStartOption>
                <compilerStartOption>-arch x86_64 -arch arm64</compilerStartOption>
              </compilerStartOptions>
              <linkerStartOptions>
                <linkerStartOption>-dynamiclib -arch x86_64 -arch arm64
                  -framework Foundation
                </linkerStartOption>
              </linkerStartOptions>
              <linkerFinalName/>
            </configuration>
            <executions>
              <execution>
                <id>test-daylib</id>
                <phase>test-compile</phase>
                <goals>
                  <goal>compile</goal>
                  <goal>link</goal>
                </goals>
                <configuration>
                  <sources>
                    <source>
                      <!-- relative to your project directory -->
                      <directory>src/main/native</directory>
                      <fileNames>
                        <fileName>Rococoa.m</fileName>
                        <fileName>ProxyForJava.m</fileName>
                        <fileName>ObjCBlocks.m</fileName>
                        <fileName>test.m</fileName>
                      </fileNames>
                    </source>
                  </sources>
                  <linkerEndOptions>
                    <linkerEndOption>-o ${project.build.testOutputDirectory}/librococoa.dylib</linkerEndOption>
                  </linkerEndOptions>
                </configuration>
              </execution>
              <execution>
                <id>daylib</id>
                <phase>prepare-package</phase>
                <goals>
                  <goal>compile</goal>
                  <goal>link</goal>
                </goals>
                <configuration>
                  <sources>
                    <source>
                      <!-- relative to your project directory -->
                      <directory>src/main/native</directory>
                      <fileNames>
                        <fileName>Rococoa.m</fileName>
                        <fileName>ProxyForJava.m</fileName>
                        <fileName>ObjCBlocks.m</fileName>
                      </fileNames>
                    </source>
                  </sources>
                  <linkerEndOptions>
                    <linkerEndOption>-o ${project.build.outputDirectory}/librococoa.dylib</linkerEndOption>
                  </linkerEndOptions>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>3.1.0</version>
            <goals>
              <goal>run</goal>
              <phase>verify</phase>
            </goals>
            <configuration>
              <target>
                <copy file="${project.build.outputDirectory}/librococoa.dylib" toFile="src/main/resources/librococoa.dylib" />
              </target>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.4</version> <!-- use 2.4 for native-maven-plugin -->
        <configuration>
          <archive>
            <manifestEntries>
              <version>${project.version}</version>
            </manifestEntries>
          </archive>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <addClasspath>true</addClasspath>
                  <mainClass>Test1</mainClass>
                </manifest>
              </archive>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <reuseForks>false</reuseForks>
          <argLine>
            -Djava.util.logging.config.file=${project.build.testOutputDirectory}/test-logging.properties
            --add-opens java.base/java.lang=ALL-UNNAMED
          </argLine>
          <trimStackTrace>false</trimStackTrace>
          <redirectTestOutputToFile>true</redirectTestOutputToFile>
          <excludes>
            <exclude>Test1.java</exclude>
          </excludes>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <includes>
                <include>Test1.java</include>
              </includes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
    </dependency>
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy</artifactId>
    </dependency>

    <dependency>
      <groupId>com.github.umjammer</groupId>
      <artifactId>vavi-commons</artifactId>
      <version>1.1.10</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
