/*
 * Copyright (c) 2022 by Naohide Sano, All rights reserved.
 *
 * Programmed by Naohide Sano
 */

package org.rococoa.cocoa.vision;

import java.util.ServiceLoader;
import java.util.function.Consumer;
import java.util.logging.Logger;

import org.rococoa.ObjCClass;
import org.rococoa.Rococoa;
import org.rococoa.cocoa.foundation.NSArray;
import org.rococoa.cocoa.foundation.NSObject;


/**
 * VNRequest.
 *
 * @author <a href="mailto:umjammer@gmail.com">Naohide Sano</a> (nsano)
 * @version 0.00 2022-10-15 nsano initial version <br>
 */
public abstract class VNRequest extends NSObject {

    private static final Logger logger = Logger.getLogger(VNRequest.class.getName());

    public static final _Class CLASS = Rococoa.createClass("VNRequest", _Class.class);

    public interface _Class extends ObjCClass {
        VNRequest alloc();
    }

    public abstract VNRequest init();

    /** Cancels the request before it can finish executing. */
    public abstract void cancel();

    /**
     * The collection of VNObservation results generated by request processing.
     * @return NSArray<VNObservation>
     */
    public abstract NSArray results();

    /** utility for only 1st */
    public Object result(Object... args) {
        NSArray results = results();
logger.finer("result: " + results.count());
        return each(results.firstObject(), args);
    }

    /** utility conversion */
    @SuppressWarnings({"rawtypes", "unchecked"})
    private static Object each(NSObject object, Object... args) {
logger.finer("result each: " + object);
        for (VNRequestConvertible convertible : convertibles) {
            if (convertible.isKindOfClass(object)) {
                return convertible.convert(convertible.cast(object), args);
            }
        }

        // TODO
        throw new UnsupportedOperationException(object.getClass().getName());
    }

    /** converters */
    @SuppressWarnings("rawtypes")
    private static final ServiceLoader<VNRequestConvertible> convertibles;

    static {
        convertibles = ServiceLoader.load(VNRequestConvertible.class);
    }

    /** utility for each */
    public void result(Consumer<Object> c, Object... args) {
        NSArray results = results();
logger.finer("result: " + results.count());
        for (int i = 0; i < results.count(); i++) {
            c.accept(each(results.objectAtIndex(i), args));
        }
    }
}
