/*
 * Copyright (c) 2022 by Naohide Sano, All rights reserved.
 *
 * Programmed by Naohide Sano
 */

package org.rococoa.cocoa.vision;

import java.util.logging.Logger;

import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;
import org.rococoa.ObjCClass;
import org.rococoa.Rococoa;
import org.rococoa.cocoa.corevideo.VideoToolboxLibrary;
import org.rococoa.cocoa.foundation.NSArray;
import org.rococoa.cocoa.foundation.NSObject;


/**
 * VNRequest.
 *
 * @author <a href="mailto:umjammer@gmail.com">Naohide Sano</a> (nsano)
 * @version 0.00 2022-10-15 nsano initial version <br>
 */
public abstract class VNRequest extends NSObject {

    private static final Logger logger = Logger.getLogger(VNRequest.class.getName());

    public static final _Class CLASS = Rococoa.createClass("VNRequest", _Class.class);

    public interface _Class extends ObjCClass {
        VNRequest alloc();
    }

    public abstract VNRequest init();

    /** Cancels the request before it can finish executing. */
    public abstract void cancel();

    /**
     * The collection of VNObservation results generated by request processing.
     * @return NSArray<VNObservation>
     */
    public abstract NSArray results();

    /** utility */
    public Pointer result() {
        NSArray results = results();
logger.finer(results.count() + ", " + results.firstObject());
        if (results.firstObject().isKindOfClass(VNPixelBufferObservation.CLASS)) {
            Pointer pixelBuffer = Rococoa.cast(results.firstObject(), VNPixelBufferObservation.class).pixelBuffer();
            PointerByReference imageRef = new PointerByReference();
            VideoToolboxLibrary.library.VTCreateCGImageFromCVPixelBuffer(pixelBuffer, null, imageRef);
            return imageRef.getValue();
        } else {
            // TODO
            throw new UnsupportedOperationException(results.firstObject().getClass().getName());
        }
    }
}
